version: '3'

services:
  transfer-service-db:
    image: postgres
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
